
const message = {
   VAL_FAILED: "validation failed",
   SUCCESS_RES: "successful",
   NOT_FOUND: "data not found",
   ERROR_OCCURRED: "An error occurred",
   SUCCESSFULLY_UPDATED: "Successfully updated",
   SUCCESSFULLY_ADDED: "Data added successfully",
   DELETE_SUCCESS: "Deleted successfully",
   DATA_NOT_FOUND: "Data is not found",
   INVALID_ID: "invalid id",
   INVALID_AGE: "invalid Age",
   INVALID_GENDER: "invalid gender",
   INVALID_NAME: "invalid name",
   SUCCESSFULLY_REGISTERED: "Data Register Successfully",
   INTERNAL_SERVER_ERROR: "Internal Server Error",
   LOGIN_SUCCESSFUL: "Login SuccessFul",
   UNAUTHORIZED: "UnAuthorized",
   INVALID_TOKEN: "Invalid Token",
   TOKEN_EXPIRED_ERROR: "Token is Expired",
   INVALID_FIRST_NAME: "firstName is inValid",
   INVALID_LAST_NAME: "lastName is inValid",
   INVALID_MOBILE_NUMBER: "mobileNumber  is inValid",
   INVALID_EMAIL: "Invalid Email Id",
   INVALID_PASSWORD: "Invalid Password",
   INVALID: "invalid data",
   SUCCESSFUL: "successful",
   INVALID_CATEGORY_NAME: "Invalid Category Name",
   INVALID_CATEGORY_ID: "Invalid Category Id",
   INVALID_PRODUCT_ID: "Invalid Product Id",
   INVALID_PRODUCT_NAME: "Invalid Product Name",
   INVALID_PRODUCT_DESCRIPTION: "Invalid Product Description",
   NO_FILES_UPLOADED: "No files were uploaded.",
   PRODUCT_IMAGE_REQUIRED: "Product Image Required",
   PRODUCT_ALREADY_EXISTS: "Product Already Exists",
   PRODUCT_NOT_FOUND: "Product Not Found",
   INVALID_IMAGE_ID: "Invalid imageId",
   IMAGE_DELETED_SUCCESSFULLY: "Image Deleted Successfully",
   USER_ALREADY_EXISTS: "User Already Exists",
   CATEGORY_ALREADY_EXISTS: "Category Already Exists",
   CATEGORY_NOT_FOUND: "Category Not Found",
   SOMETHING_WENT_WRONG: "Something went wrong",
   USER_NOT_FOUND: "User Not Found",
   INVALID_USER_ID: "Invalid User Id",
   IMAGE_NOT_FOUND: "Image Not Found",
   EMAIL_SENT_SUCCESSFULLY: "Email Sent Successfully",
   PASSWORD_NOT_MATCHED: "Password not matched",
   INVALID_NEW_PASSWORD: "Invalid New Password",
   INVALID_CONFIRM_PASSWORD: "Invalid Confirm  Password",
   CARD_TOKEN_ERROR: "some error in cardToken",
   PAYMENT_SUCCESSFUL: "payment successful",
   PAYMENT_FAILED: "payment failed"

}

export default message;